### ISSUE TITLE
現状のサイトについて把握・2016版について検討する

### ISSUE THREAD

**Issue by keitakawamoto** [ito-artsfarm/2016website#1]
さあ、やりましょう！
- [現状のサイト](http://www.ito-artsfarm.com/)の内容を把握・整頓するところから始める

**Comment by keitakawamoto** [comment]
## ソーシャル

すでに存在する。
リンクは公式サイトのフッタに設置されている
- [Youtube](https://www.youtube.com/channel/UChYMr26nJDUwromf-owl6fw)
- [Twitter](https://twitter.com/ItoArtsFarm)
- [Facebook](https://www.facebook.com/%E7%B3%B8%E5%B3%B6%E8%8A%B8%E8%BE%B2-143252965796552/timeline/)

**Comment by ecogrammer** [comment]
公式URL http://www.ito-artsfarm.com
http://ito-artsfarm.com でサイトが見られない（もったいない）

**Comment by keitakawamoto** [comment]
@ecogrammer 
www取り払って http://ito-artsfarm.com に統一（短くなる）し、http://www.ito-artsfarm.com にアクセスしてもリダイレクトするようにするとかどうでしょう。

**Comment by keitakawamoto** [comment]
## 2016サイト現状

#### 基礎
- WordPressで構築されている
- テーマカラー：緑？

#### トップについて
- キービジュアルは風景のスライドになっている
- 糸島国際芸術祭2016開催告知
- about（名称・開催日時・開催場所）
- アーティスト　項目のみ内容なし
- イベント　項目のみ内容なし

#### フッタ
- 最近の投稿
- タグクラウド
- 検索窓
- ソーシャルリンク
- 著作権表記
- 右下にヘッダへ戻るボタン

#### グローバルメニュー
- ニュース
  - スタッフブログ
- 糸島農芸について
  - 農芸メンバー
  - 糸島農芸2012（リンク）
  - 糸島農芸2014 糸島国際芸術祭（リンク）
  - コンタクト（お問い合わせフォーム・アクセスマップ）

`2012` , `2014` のコンテンツについても把握する

**Comment by ecogrammer** [comment]
- https://github.com/ito-artsfarm/2016website/issues/1#issuecomment-147560931 rewrite rule 適用済
- staging.ito-artsfarm.com 用意（basic認証有）

**Comment by keitakawamoto** [comment]
@ecogrammer あざます！

> #1 (comment) rewrite rule 適用済

おっ、`www` 有りのほうをメインにしたんですね。これまでそうだったので、そのままのほうが確かに良さそうですね。

**Comment by ecogrammer** [comment]
ですねー

**Comment by ecogrammer** [comment]
なんとなくかっこいいと思ったサイト
- ベネッセアートサイト直島 http://benesse-artsite.jp/
  
  シンプルでみやすく整理されている
  <img width="1276" alt="2015-11-10 21 40 36" src="https://cloud.githubusercontent.com/assets/90103/11062631/c72d19f8-87f3-11e5-8638-f2cf49097e98.png">
- 札幌国際芸術祭 http://www.sapporo-internationalartfestival.jp/2014/
  
  こちらも見やすい、フォントの使い方が良い
  <img width="1274" alt="2015-11-10 21 45 44" src="https://cloud.githubusercontent.com/assets/90103/11062721/92ec8696-87f4-11e5-9a54-13e1b1a1f93d.png">

**Comment by ecogrammer** [comment]
九州界隈の芸術祭、アート活動
- 国東半島芸術祭 http://kunisaki.asia/
  <img width="1276" alt="2015-11-10 21 40 19" src="https://cloud.githubusercontent.com/assets/90103/11062621/b8889ef4-87f3-11e5-9046-8c19d9831774.png">
- 熊本河原町文化開発研究所 http://kumamoto-kawaramachi.net/
  <img width="863" alt="2015-11-10 21 43 29" src="https://cloud.githubusercontent.com/assets/90103/11062674/20e26de0-87f4-11e5-8c13-41f03412fce4.png">

**Comment by keitakawamoto** [comment]
@ecogrammer 利用可能な写真素材について共有して欲しいです。すべてを把握したい。

**Comment by makizonokenji** [comment]
2016年のサイトに、下記githubへのリンクをつけて欲しいです。
https://github.com/ito-artsfarm/ItoArtsFarm2016

リンクボタンやバナーなどでもいいですし
↓サイトのようにラベルがあってもいいかもしれませんね。
http://unfoldingmaps.org/

**Comment by keitakawamoto** [comment]
@makizonokenji リンクいいですね！了解です :ok_woman:

**Comment by ecogrammer** [comment]
@keitakawamoto 
DropBoxの共有フォルダに招待しました。2016/photos に素材になりそうそうな写真と置いています。イメージ、サイトのモック程度なら使えるかな..。

**Comment by keitakawamoto** [comment]
@ecogrammer 確認しました。あざます！

**Comment by ecogrammer** [comment]
:+1:

**Comment by keitakawamoto** [comment]
## キャッチコピー、2016もほしい

![image](https://cloud.githubusercontent.com/assets/1661325/12066446/60e0b7d0-b02b-11e5-806e-05226a54d659.png)

やはりあるのいいですね。
キャッチだけでどういうものなのか内容が伝わると最高です。

**Comment by ecogrammer** [comment]
確かにキャッチコピーはある方がコンセプトが伝わってきますねー。
@makizonokenji 今年のキャッチコピーって決まっていたりしますか？

**Comment by makizonokenji** [comment]
アサヒアートフェスティバル（アーツプロジェクトのネットワーク）に申請する時に決まると思いますが、それまでは「山の資源を考えなす」でお願いします！

**Comment by keitakawamoto** [comment]
了解しました！（なす、は `成す` ということですね）

**Comment by ecogrammer** [comment]
成す のことだと思う :+1:

**Comment by keitakawamoto** [comment]
:+1:

**Comment by keitakawamoto** [comment]
## 2012コンテンツ
- トップ
  - キービジュアル
  - コンテンツへのリンク
  - 新着情報
  - ソーシャルフィード
  - 助成・特別協賛表示
  - 後援表示
  - 協賛表示
- 趣旨／目的
  - 参加者略歴
  - 趣旨／目的（トップからしかリンクされていない）
- 2012糸島芸農アーカイブ
  　- 各作品の詳細な紹介
- プログラム
  - 月別に何をするかを紹介
  - 糸島芸農プレイベント告知
  - アートの種まき展告知
  - アートの草むしり
  - アートの収穫祭
- BLOG
- パートナー助成・協賛
- 運営団体

## 2014コンテンツ
- トップ
- ニュース
  - スタッフブログ
  - イナリサーチ（松末稲荷聞取り調査）
- スケジュール
  - スケジュール一覧・各詳細へのリンク
  - 参加アーティスト紹介
  - 内山 節　講演会 告知
- チケット
- 糸島芸農について
  - スポンサー
  - 運営メンバー

**Comment by makizonokenji** [comment]
ごめんなさい！

×「山の資源を考えなす」
↓
○「山の資源を考えなおす」

です！お正月にまでありがとうございます！！！

**Comment by ecogrammer** [comment]
2012年は、コンテンツが重複したりしてゴチャゴチャしていました。それを教訓として2014年はスッキリさせていますねー。

**Comment by keitakawamoto** [comment]
@ecogrammer そのようですね。かなりスッキリ。

**Comment by keitakawamoto** [comment]
> 「山の資源を考えなおす」

了解です！
しかし、最初の印象では、「考え直してどうするのだろう？」という印象でした。
その答えはトップページでコンテンツについて簡潔に説明すること（糸島農芸とは？など）で伝えることができます。
しかしキャッチだけ見てその他をよく見ない場合、伝わりにくいかも、という懸念があります。。。

**Comment by keitakawamoto** [comment]
# 2016サイト構成・内容整頓案

## 構成
- 引き続きWordPressで構築
- ベースは１ページ縦長構成・レスポンシブ対応
  - メニューからはページ内リンク
  - 各項目詳細はリンク形式（専用ページ用意）

## コンテンツ
- ヘッダ
  - ロゴ
  - グローバルメニュー
  - 検索窓
- キービジュアル・キャッチコピー
- 開催告知(日時紹介込み)
- 糸島国際芸術祭とは？（スポンサーや運営メンバーページへの導線あり）
- イベント/スケジュール（アーティスト紹介や告知込み・アクセスも）
- アーティストピックアップ
- 新着情報（ブログタイトル最新数件表示）
- チケット
- ブログ
- コンタクト
- フッタ
  - github・Twitter・Youtube・Facebookアイコンリンク
  - 2012/2014サイトへのリンク
  - ヘッダへ戻るボタン
  - 著作権表記

**Comment by ecogrammer** [comment]
良さそう :+1:

**Comment by makizonokenji** [comment]
@keitakawamoto 

＞了解です！
＞しかし、最初の印象では、「考え直してどうするのだろう？」という印象でした。
＞その答えはトップページでコンテンツについて簡潔に説明すること（糸島農芸とは？など）で伝える＞ことができます。
＞しかしキャッチだけ見てその他をよく見ない場合、伝わりにくいかも、という懸念があります。。。

おっしゃる通りです。「山の資源を考えなおす」は今年のテーマの一つで、展覧会を開催するまでのリサーチのための”切り口の一つ”ですね。そこから、ワークショップやトーク、作品などを通して、「どうなるの？」への解を出していこうと思ってます。

キャッチコピーはアサヒアートフェスティバル（アーツプロジェクトのネットワーク）への申請後、2月1日（月）までには決めれる予定なので、それまでいったん○○○などの表記は可能でしょうか？？

**Comment by torao2003** [comment]
github、やっと参加の仕方がわかりました～
2016年版のウェブサイトでの希望なんですが、うまく伝わるかどうかわからないけど、2012、2014を含めて、それから将来を見据えた「アーカイブ」が作れるといいなあ、とか。過去の参加作家の作品写真や動画とか。松末周辺で作品制作に使える場所や素材とか人物とか。短期集中的なイベントの告知、宣伝だけでなくて、中長期的に、過去に遡ったり将来に備えたりするためのサイト。
規模は全然違うけど、発想とか機能としては、google cultural instituteのようなものかな。
https://www.google.com/culturalinstitute/u/0/home?hl=ja

**Comment by keitakawamoto** [comment]
@makizonokenji 

> それまでいったん○○○などの表記は可能でしょうか？？

開発中の環境でなら可能です！了解しました :+1: 
外部ユーザーにも見える状態で公開するときは、また相談させていただきますね。
しかしおそらくそれより先に 2/1 がくると思うので、心配いらなそうです。

**Comment by keitakawamoto** [comment]
@torao2003 

> 2012、2014を含めて、それから将来を見据えた「アーカイブ」が作れるといいなあ、とか。過去の参加作家の作品写真や動画とか。

素晴らしいと思います。
ユーザーがそれを見ることで、糸島農芸でどのようなことが行われているかさらに伝わりやすくなります。
どのようなものにするか検討します！

@ecogrammer まずは協力していただいて 2012,2014すべてのアーカイブを別issueでまとめたいのですが、その進め方でいいでしょうか。

**Comment by keitakawamoto** [comment]
アーカイブサイトを作るか、2016サイト内にアーカイブページとするか。
2017といった次回以降にまたアーカイブページを作るのもなんかわかりにくいので、糸島農芸アーカイブサイトを別に作って、2016サイトからリンクさせるほうがわかりやすそう。
2016サイトは2016のイベントに関してのみに絞ったほうがより伝わりやすいと考える。

**Comment by keitakawamoto** [comment]
アーカイブサイトを作る場合、 [tumbler](https://www.tumblr.com/)を使いたい。過去作品全てを把握・データ受け取り次第構築していきたい。
https://www.tumblr.com/themes/tagged/free?language=ja_JP

tumblerであれば
-  **SNSなので作品の拡散が容易 = 認知向上のための土台になる**
- 完成されたサービスなので管理が容易

などというメリットがある。

**Comment by ecogrammer** [comment]
アーカイブは @keitakawamoto の言う通り2016サイトとは別がいいでしょうねー。
なので tumbler でもいいし、archive.ito-artsfarm.com とかでアーカイブサイトを設ける。
ですかね。

**Comment by keitakawamoto** [comment]
@ecogrammer tumblerにもサブドメイン設置できるので、ドメインに関してはどの手段でも `archive.ito-artsfarm.com` にできそうですね。
http://tsurudama.jp/2013/12/12/tumblr-%E3%81%AB%E3%82%B5%E3%83%96%E3%83%89%E3%83%A1%E3%82%A4%E3%83%B3%E3%82%92%E5%89%B2%E3%82%8A%E5%BD%93%E3%81%A6%E3%82%8B3%E3%82%B9%E3%83%86%E3%83%83%E3%83%97/

**Comment by makizonokenji** [comment]
糸島芸農2016のタイトル＜キャッチコピー＞決まりました！

糸島国際芸術祭2016 糸島芸農
発酵する地平

Itoshima International Art Festival 2016 Itoshima Arts Farm
fermenting perspectives

上記タイトルに至った経緯　※大澤さんのFB投稿より

＊

昨夜の会議で、糸島芸農2016のテーマは「発酵する地平」となりました。
どうして、「発酵する地平」になったのかと言いますと。
実は、糸島芸農のメイン会場の権九郎稲荷神社のお手洗いが、いわゆる「ぼっとんトイレ」で、実行委員会代表の松崎氏 Hirofumi Matsuzaki は、会議で「あのぼっとんトイレ、どげんかせんと…」「やっぱ、ぼっとんは、臭いがキツかです…」「ぼっとんだけはなんとかせんと…」と、口を開けば、ぼっとんぼっとんぼっとんぼっとんとしつこくて。
松崎さんが小学生くらいまでは、家に肥溜めがあり、その肥を畑に使っていたという話で。いま、下水道整備や汲み取り業者のおかげで、うんこやおしっこが食べ物の栄養になるということも見えない。汚いものは見えない場所に遠ざけられて、人間の排泄と自然の再生との循環が、断絶しているんだね、という話になりました。
そこで私たち芸農メンバーは、排泄から再生の過程の「発酵」に目を向けました。例えば、田んぼや畑に必要な堆肥は、動物の排泄物などの有機物が発酵することで分解されて、作物の生育に必要な土の養分になるというわけです。
ところが「発酵」と「腐敗」は実は微生物の分解作用という点では同じで、＜結局、人類に有益なものを発酵、有害なものを腐敗と呼んでいるに過ぎない＞らしい。

https://ja.wikipedia.org/wiki/%E8%85%90%E6%95%97#.E7.99.BA.E9.85.B5.E3.81.A8.E8.85.90.E6.95.97

これ、世の中に対するアートの作用と似てるなぁと思ったわけです。例えば、過疎化や高齢化など、活力を失う地域の中で、アートがどんな役割を果たすのかを考えたとき、アートやアーティストが微生物のように作用することで「発酵」を起こすことができないだろうか、と考えたわけです。
人によってはそれが「腐敗」に見えるかもしれない。でも、腐敗なのか発酵なのかは、そこで作用するアート次第ではないか。アートの力が足りなければ腐敗に、アートの力があれば発酵に。そこを、敢えて見せようじゃないか、と。
というわけで、松崎さんの「ぼっとんトイレ」の悩みから「発酵する地平」という壮大なテーマに落ち着いた今年の糸島芸農を、ぜひ、お楽しみに〜！

**Comment by makizonokenji** [comment]
「発酵する地平」にふさわしいキーとなるビジュアルも必要かと思いますので、少々お待ちください！イメージをかたちにする際に、参考になれば幸いです！

**Comment by makizonokenji** [comment]
一つ目、参考までに！
https://www.dropbox.com/home/%E3%82%A2%E3%83%BC%E3%83%84%E3%83%95%E3%82%A1%E3%83%BC%E3%83%A0/2016/photos?preview=%E9%A2%A8%E6%99%AF.jpg

**Comment by keitakawamoto** [comment]
@makizonokenji ありがとうございます！了解しました。

**Comment by makizonokenji** [comment]
英語のタイトルは下記でお願いします！

Itoshima International Art Festival 2016 Itoshima Arts Farm
fermenting perspectives

**Comment by keitakawamoto** [comment]
@makizonokenji 英語タイトル了解です。他言語化時に掲載しようと思います！

**Comment by keitakawamoto** [comment]
- [2016版サイトレイアウト](https://github.com/ito-artsfarm/2016website/issues/6)
- [テーマ実装](https://github.com/ito-artsfarm/2016website/issues/8)

上記にて進行。
