### ISSUE TITLE
サポートスタッフ「いっきさん」を募集ページのキャプチャ画像がリンク切れ

### ISSUE THREAD

**Issue by shoyan** [ito-artsfarm/2016website#10]
サポートスタッフ「いっきさん」を募集ページのキャプチャ画像がリンク切れしています。
http://www.ito-artsfarm.com/2016/08/28/supportstaff/

<img width="643" alt="2016-08-29 13 00 03" src="https://cloud.githubusercontent.com/assets/1150041/18040438/d6978dfc-6de8-11e6-9f03-67d97fa6d2ef.png">

**Comment by shoyan** [comment]
@ecogrammer こちら対応お願いできますかー？

**Comment by ecogrammer** [comment]
@shoyan 
今表示したら チャプチャ生成されています。 多分ショーやんが表示したとき、チャプチャ生成（GDlibでの処理か？）ができなかったのではないかと思います。

**Comment by shoyan** [comment]
なるほどー。アクセスし直したら表示されました。
ここの画像認証外してもいいかもしれませんね。

**Comment by ecogrammer** [comment]
@shoyan 残念ながら外すとスパムが来ちゃうんですよ。。

**Comment by shoyan** [comment]
おぉ、そうだったのですね。。。
