### ISSUE TITLE
ロゴに関する情報

### ISSUE THREAD

**Issue by keitakawamoto** [ito-artsfarm/2016website#3]
既存のロゴについて知る

**Comment by keitakawamoto** [comment]
製作者は先崎さん。総務大臣賞を受賞したいろいろなプロダクトで活躍中のクリエイター。
- [糸島農芸のロゴついて](http://tetusin.com/leaflet/20130411_1824481752/)
- [先崎さん総務大臣賞　日本観光ポスター ](http://www1.saga-s.co.jp/news/saga.0.2461471.article.html)

**Comment by ecogrammer** [comment]
糸島芸農以外にも [九州ちくご元気計画](http://kyushu-chikugo.net/) など、多くのプロジェクトに携わっています。

**Comment by keitakawamoto** [comment]
![image](https://cloud.githubusercontent.com/assets/1661325/10472070/0c3edd7c-7257-11e5-9faa-847c8bc950ee.png)

このマークは、どのような意図でこのような図形になっているのでしょう？
コンセプトなどを知りたいです。

**Comment by ecogrammer** [comment]
直接先崎さんに聞いた訳じゃないけど、稲の（下のロゴ）実りに人（上のロゴ）が喜んでいるイメージだった気がします。

<img width="184" alt="2015-11-10 21 36 38" src="https://cloud.githubusercontent.com/assets/90103/11062554/2824e520-87f3-11e5-91b2-3343531ddeed.png">
- （田畑を）耕し、
- （人は喜びを）芸す。

**Comment by keitakawamoto** [comment]
なるほど。ありがとうございます！
下の縦線は、地図記号の `田んぼ` からですね。把握しました。
