### ISSUE TITLE
サーバー移設をやる

### ISSUE THREAD

**Issue by ecogrammer** [ito-artsfarm/2016website#5]
## 内容

表題の通り、ロリポップで運用しているので新サーバー（次世代ホスティング）にサーバーの移設を実施する。表示速度、レスポンスの向上が期待されます。 :+1: 
参考 https://lolipop.jp/nextgen/

**Comment by ecogrammer** [comment]
@studiokura 
11/28,11/29 辺りに、糸島芸農で使っているサーバーの移設を行っちゃいます。

**Comment by keitakawamoto** [comment]
ﾔﾌｰ!

**Comment by ecogrammer** [comment]
### PageSpeed Insights

#### 移設前

<img width="1191" alt="2015-12-01 7 52 38" src="https://cloud.githubusercontent.com/assets/90103/11487165/b7d27198-9800-11e5-974a-86159c9e96e3.png">
<img width="1179" alt="2015-12-01 7 52 23" src="https://cloud.githubusercontent.com/assets/90103/11487173/c07600d0-9800-11e5-90c8-eb9aba029f71.png">

#### 移設後

<img width="1172" alt="2015-12-01 8 27 09" src="https://cloud.githubusercontent.com/assets/90103/11487877/ad58a99e-9805-11e5-9b59-48fa1056ffdb.png">
<img width="1200" alt="2015-12-01 8 27 32" src="https://cloud.githubusercontent.com/assets/90103/11487884/b65ea16a-9805-11e5-944c-1562a4f8550b.png">

**Comment by ecogrammer** [comment]
### GTmetrix

#### 移設前

<img width="1037" alt="2015-12-01 7 51 47" src="https://cloud.githubusercontent.com/assets/90103/11487191/d39fdce4-9800-11e5-8e64-2c3b77a8ad49.png">

#### 移設後

<img width="1043" alt="2015-12-01 8 33 42" src="https://cloud.githubusercontent.com/assets/90103/11487963/492bcc7a-9806-11e5-8115-3b8da2d09feb.png">

**Comment by ecogrammer** [comment]
- 移設時間約10分（その間は 403 NotFound になるので要注意）
- 移設しただけでスコアが上がった。
- Load Timeも2.x台に改善された。

**Comment by keitakawamoto** [comment]
LGTM :+1:

**Comment by shoyan** [comment]
いいですね〜 :+1:

**Comment by ecogrammer** [comment]
完了！
