### ISSUE TITLE
2016版サイトレイアウト

### ISSUE THREAD

**Issue by keitakawamoto** [ito-artsfarm/2016website#6]
構成については https://github.com/ito-artsfarm/2016website/issues/1#issuecomment-168777963

**Comment by ecogrammer** [comment]
レイアウト、モック作る時cacoo使うんだけど、みんな何使っているのか興味あるます。

**Comment by keitakawamoto** [comment]
僕はPhotoshopだったり、最初からhtml/cssでレイアウトしたりだったりですね〜

**Comment by keitakawamoto** [comment]
## テイスト基礎

装飾テイストの基礎としては http://tetusin.com/leaflet/20130411_1824481752/ を受け継ぐ

**Comment by ecogrammer** [comment]
:+1:

**Comment by keitakawamoto** [comment]
# レイアウト完成

@makizonokenji @ecogrammer お待たせして申し訳有りません :bow: 
サイトレイアウト・装飾案ができました。

![_02](https://cloud.githubusercontent.com/assets/1661325/13386093/cfc6ffee-deeb-11e5-9c4d-4c505f3ffd3f.png)

## 注意点：過去のイベントなどをサンプルとして挿入しています

過去のイベントなどを挿入サンプルとして流用し、サイトが最終的にどうなるかイメージできるようにしました。

## まずは背景画像をブラウザいっぱいに表示
- サイトにアクセスした直後は背景画像をブラウザいっぱいに表示させます。
- 糸島の大地、画面いっぱいにひろがる作物・山・空といった印象付けの効果が得られます。
- ごちゃごちゃしていないので、テーマ・概要・開催日に注目させやすくなります。
- 「スクロールして進む」ということが伝わるように、画面下部にその案内を設置しています。

![_02 2](https://cloud.githubusercontent.com/assets/1661325/13386096/d9282fd6-deeb-11e5-8bfe-ea2ed4cde0f8.png)

### まずは「糸島農芸って？？」を解決

知らない人にとっては「糸島農芸」といわれても、一体なんなのかさっぱりわかりません。
それを解決した上でイベント紹介などができるよう、 **「糸島国際芸術祭とは？」** という項目を一番目に配置しました。
そして「発酵する大地」についても同様で、キャッチだけでは狙い・意図・全貌が伝わりません。
なのでそのキャッチに対する想い・願いはこうである、という**「発酵する大地？」**という背景解説の項目も用意しました。

### コンテンツの順番

前述の通り、疑問を解消した上で
1. いつ開催するの？ -> 開催告知
2. アーティストって誰？ -> アーティスト紹介
3. そのアーティストたちがいつ、何するの？ -> イベント紹介
4. いいな、いこうかな -> チケット販売
5. 興味ある人に向けて -> スタッフブログ、お問い合わせ
6. 最後まで見た人用に -> チケット販売

という流れから内容の並び順を決めました。

### ヘッダ部分は追従

http://shop-pro.jp/ と同じように、

![image](https://cloud.githubusercontent.com/assets/1661325/13383291/cfce6994-deca-11e5-981e-639c4b355fef.png)

このヘッダ部分はスクロールに合わせて付いてくるので、いつでも望んだ項目に遷移するとこが出来る・いつでもチケット購入ができます。

**Comment by shoyan** [comment]
@keitakawamoto 

素晴らしいですね〜 :+1: 
2点、気になった点があるので記入します。

トップの「。」について
「発酵する地平。」と「2016年10月開催。」の「。」をつけている意味はありますか？

説明について
「自然豊かな糸島二丈〜芸術の祭典、今年もやります。」の説明なのですが、糸島農芸の説明と今年やるという意味が1つの文章に入ってしまっています。
今年やるということは下の2016年10月開催でわかるので、「今年もやります」はあえていれる必要はないのではと思いました。
（個人的に「今年もやります」は少し安っぽいイメージに感じました）

**Comment by keitakawamoto** [comment]
@shoyan 

> 「発酵する地平。」と「2016年10月開催。」の「。」をつけている意味はありますか？

句点があることで 「ドン！」という効果がある。
あと「文章はそこまでですよ」ということが明確に分かる。

> 「自然豊かな糸島二丈〜芸術の祭典、今年もやります。」の説明なのですが、糸島農芸の説明と今年やるという意味が1つの文章に入ってしまっています。今年やるということは下の2016年10月開催でわかるので、「今年もやります」はあえていれる必要はないのではと思いました。（個人的に「今年もやります」は少し安っぽいイメージに感じました）

簡潔に「概要はこうである糸島農芸が開催される」ということを説明したい。どんな文章がいいと思う？

**Comment by shoyan** [comment]
@keitakawamoto 

> 句点があることで 「ドン！」という効果がある。
> あと「文章はそこまでですよ」ということが明確に分かる。

「！」であれば「ドン！」という効果があると思うけれど、「。」に「ドン！」という効果はあるのかな。「。」は文章が終わりという意味に使うのでは。
あと、「文章はそこまでですよ」というのは、「。」がなくても明らかにわかるのではと思った。

「。」をつけること自体に反対ではないです。
自分は見出しに「。」が使われるのにあまり慣れていないだけなので気になっただけです（自分の感覚の問題）。

> 簡潔に「概要はこうである糸島農芸が開催される」ということを説明したい。どんな文章がいいと思う？

なるほど。例えば、以下はどうかな。
「糸島農芸とは、自然豊かな糸島二丈松末地区で行われる、国内外の作家が集まり作品を展示する芸術の祭典です。」

国内外を少し強調してみる。
- 「糸島農芸とは、自然豊かな糸島二丈松末地区で行われる、国内外の作家が集まり作品を展示するインターナショナルな芸術の祭典です。」
- 「糸島農芸とは、自然豊かな糸島二丈松末地区で行われる、国内外の作家が集まり作品を展示する国際的な芸術の祭典です。」

どんな作品が展示されるんだろう？

**Comment by keitakawamoto** [comment]
> 「！」であれば「ドン！」という効果があると思うけれど、「。」に「ドン！」という効果はあるのかな。「。」は文章が終わりという意味に使うのでは。あと、「文章はそこまでですよ」というのは、「。」がなくても明らかにわかるのではと思った。「。」をつけること自体に反対ではないです。
> 自分は見出しに「。」が使われるのにあまり慣れていないだけなので気になっただけです（自分の感覚の問題）。

確かにドンについては効果はないかも。しかし文字の終わりで取り付けることは間違いではない、そして個人の感覚の指摘の部分（根拠がない）なので、現時点では句読点アリでいこう。

> なるほど。例えば、以下はどうかな。

なるほど。 @makizonokenji  @ecogrammer のご意見もお伺いしたい部分。お二方、冒頭の説明についてどうお考えですか？

**Comment by ecogrammer** [comment]
地平感が出ていていいですね！適度に余白が出て見やすい構成だと感じました！！

**Comment by keitakawamoto** [comment]
![image](https://cloud.githubusercontent.com/assets/1661325/13388079/63de8df0-df00-11e5-8870-73093d7494e6.png)

ちょっと区切り線が薄すぎたかも。もう少し濃くします〜

**Comment by ecogrammer** [comment]
チケット購入の背景色、リンク色は発酵をイメージしているとか？

**Comment by ecogrammer** [comment]
@shoyan 

> どんな作品が展示されるんだろう？

これに関してはまだ精査中なので具体的には言えない(publicだし)と思いますが、例年絵画、写真、オブジェクト（屋内外での展示作品）、ライブ演奏、ライブパフォーマンス、田植え・草むしり（展示ではないけど表現の１つ）等、 **アートまたは農という幅広い括り** でやっているのであまり作品そのものは意識しない方が良いかも。

**Comment by keitakawamoto** [comment]
> チケット購入の背景色、リンク色は発酵をイメージしているとか？

メイン画像の世界観と調和する色を選択しました。
調和することによって一体感を得ることができ、ユーザーは落ち着いて閲覧することができます。
メイン画像が「発酵の地平」感があるので、結果的には「リンク色は発酵をイメージしている」とも言えますね。

**Comment by ecogrammer** [comment]
:+1:  良いねー

**Comment by makizonokenji** [comment]
遅くなりました！
いただいたレイアウト案についてPDFをお送りします！

●デザインはOKです！
●メニューや表示方法（現段階）での希望を書いています。

できればこの情報で速い段階でwebサイトをリリースしていければと思います。
※現在、芸術祭開催までの「イベント」、開催中の「イベント」もなども企画中です。

ご不明な点がありましたら、リアクションお願いいたします！

[サイト案修正_0421.pdf](https://github.com/ito-artsfarm/2016website/files/228462/_0421.pdf)

**Comment by makizonokenji** [comment]
遅くなりました！
いただいたレイアウト案についてPDFをお送りします！

●デザインはOKです！
●メニューや表示方法（現段階）、追加希望を書いています。

できればこの情報で速い段階でwebサイトをリリースしていければと思います。
※現在、芸術祭開催までの「イベント」、開催中の「イベント」もなども企画中です。

ご不明な点がありましたら、リアクションお願いします！

[サイト案修正_0421.pdf](https://github.com/ito-artsfarm/2016website/files/228536/_0421.pdf)

**Comment by keitakawamoto** [comment]
@makizonokenji 
わかりました！PDF確認します。
現在実装できるように作業中ですので、そちらにも反映させますね。
変更した際に共有いたします！

**Comment by keitakawamoto** [comment]
@makizonokenji 

![image](https://cloud.githubusercontent.com/assets/1661325/14694183/da29da28-07a0-11e6-9b76-cde2603ee759.png)

`これまでの開催`項目について把握いたしました。
ただ、 `(c)糸島国際芸術祭2016 糸島芸農` というコピーライト（著作権表示）はあるのがwebサイトでは（絶対ではないが）お約束なのですが、コピーライトはそのまま残すのはいかがでしょうか？

**Comment by makizonokenji** [comment]
さっそくありがとうございます！コピーライトはそのままでよろしくお願いします！

**Comment by keitakawamoto** [comment]
了解です！

**Comment by keitakawamoto** [comment]
## メモ

#### 会場アクセスについて
- `会場アクセス` は開催概要と結合したほうが良い
  - 理由：開催概要で展示場所まで示しているので、そこでアクセスについても知ることができたほうが親切であるため
  - 分割する理由が特にない
  - 開催1ヶ月前に `開催概要` に表示したい

#### メニューについて

![image](https://cloud.githubusercontent.com/assets/1661325/15654342/575079ca-26ce-11e6-8ab9-216d408a61e8.png)

この量では横におさまらない。
また、画面の幅を縮小した場合に柔軟に対応できない。
さらに、項目数が多すぎると見たい情報を探すのが大変。
よって以下のように大項目・小項目に分割し、ロールオーバーで小メニューを出す。

![image](https://cloud.githubusercontent.com/assets/1661325/15654364/8abf7b26-26ce-11e6-9863-89d30ffed284.png)
- 糸島芸農とは？
- 開催概要
  - アーティスト
  - イベント/スケジュール
- プロジェクト
- 運営
  - 運営メンバー
  - ブログ
  - お問い合わせ
  - これまでの開催
- チケット購入
- プレスリリース

**Comment by makizonokenji** [comment]
＞会場アクセス は開催概要と結合したほうが良い

確かに、項目数が多すぎると見たい情報を探すのが大変ですね！
提案ありがとうございます！

そのようにしてもらえると嬉しいです。
よろしくお願いします！

**Comment by keitakawamoto** [comment]
おおお、確認ありがとうございます！ 🙇 
他にもご提案できる部分があればさせていただきますー！

**Comment by makizonokenji** [comment]
遅くまでありがとうございます！！
何かアドバイスあれば、ぜひよろしくお願いします！！

**Comment by keitakawamoto** [comment]
### 項目部分のタイトルについて

![image](https://cloud.githubusercontent.com/assets/1661325/15655916/d144be90-26dc-11e6-820f-f49bb9f16447.png)

もともと画像文字にしていた理由は

> 装飾テイストの基礎としては http://tetusin.com/leaflet/20130411_1824481752/ を受け継ぐ

というものがあったが
- 2016年のポスターテイストは上記とは限らない
- 画像文字は修正に柔軟に対応できない
- 音声認識ソフトにやさしくないと思われる
- 拡大した際に解像度の関係でぼやけて表示される
- スマホで見たときなど、環境変動時にテキスト文字のほうが確実に視認しやすい

といった理由から画像文字はやめて以下のような最近の主流であるテキスト文字にする。

![image](https://cloud.githubusercontent.com/assets/1661325/15655897/af71765a-26dc-11e6-9a0e-687c810a7a7a.png)

**Comment by keitakawamoto** [comment]
## TODO

明日以下の二つのロゴの大きいサイズのデータがないか確認する。
現在サイズが小さく解像度が低いので、あまり綺麗に表示されない。

![image](https://cloud.githubusercontent.com/assets/1661325/15656034/f25ed0ba-26dd-11e6-85d0-3515d4d117fa.png)

**Comment by makizonokenji** [comment]
了解しました！FBスタッフルームの方にロゴの画像お送りしました。
後援の「九州大学大学院芸術工学研究院」については、ロゴが無いか確認中です。

**Comment by makizonokenji** [comment]
kawamotoさん
AAF関連で、下記リンクバナーを設置することは可能でしょうか？？
設置場所はフッター部分をイメージしています。
それぞれ、サイズに合わせて3種の中から選べるようになっています。

①熊本地震　AAFネットワーク活動支援募金公式リンクバナー

貼り付けコード1
<a href="http://www.asahi-artfes.net/news/2016/04/aaf-15.html" target="_blank"><img border=0 src="http://www.asahi-artfes.net/banner/banner_kumamoto_normal.png" alt="Asahi Art Festival"></a>

貼り付けコード2
<a href="http://www.asahi-artfes.net/news/2016/04/aaf-15.html" target="_blank"><img border=0 src="http://www.asahi-artfes.net/banner/banner_kumamoto_mini.png" alt="Asahi Art Festival"></a>

貼り付けコード3
<a href="http://www.asahi-artfes.net/news/2016/04/aaf-15.html" target="_blank"><img border=0 src="http://www.asahi-artfes.net/banner/banner_kumamoto_square.png" alt="Asahi Art Festival"></a>

②AAF2016の公式リンクバナー

貼り付けコード1
<a href="http://www.asahi-artfes.net/" target="_blank"><img border=0 src="http://www.asahi-artfes.net/banner/banner_aaf2010_normal.gif" alt="Asahi Art Festival"></a>

￼貼り付けコード2
<a href="http://www.asahi-artfes.net/" target="_blank"><img border=0 src="http://www.asahi-artfes.net/banner/banner_aaf2010_mini.gif" alt="Asahi Art Festival"></a>

￼貼り付けコード3
<a href="http://www.asahi-artfes.net/" target="_blank"><img border=0 src="http://www.asahi-artfes.net/banner/banner_aaf2010_square.gif" alt="Asahi Art Festival"></a>

**Comment by keitakawamoto** [comment]
@makizonokenji 
可能です！熊本支援素晴らしいです。
これはユーザーに目に付いたほうがより効果的と思いますので、下部は下部でもフッタの少し上に項目付きで設置するのはどうでしょうか。
※サイト全体に余白を多めにとって読みやすくしているので、フッタもそれに揃え余白多めです。

![image](https://cloud.githubusercontent.com/assets/1661325/15660038/9807d458-2710-11e6-9adf-6682b9d793f5.png)

この場合、バナーが小さいので横に長いバナーが望ましいですが、こちらでバナーを作成させていただくことはできませんでしょうか。
（作成する場合は、基本デザインは同じもので構成します）

**Comment by keitakawamoto** [comment]
## 協賛等

FBより

> プレスリリースにもありますが、ロゴの配置は下記の要にお願いします。
> 
> 助成：アサヒ・アート・フェスティバル2016
> 協賛：Studio Kura
> 後援：九州大学大学院芸術工学研究院、九州大学ソーシャルアートラボ

![13335850_727553700681630_2209902255617951580_n](https://cloud.githubusercontent.com/assets/1661325/15660116/59420020-2712-11e6-89ec-52bebc9fa1ed.jpg)
![13343040_727553967348270_5951015597146579126_n](https://cloud.githubusercontent.com/assets/1661325/15660117/59427d3e-2712-11e6-9b3e-532ded67e9c6.jpg)
![13327630_727553960681604_5297228450072012768_n](https://cloud.githubusercontent.com/assets/1661325/15660118/59434106-2712-11e6-95a8-3bf705ddbcc7.jpg)

**Comment by makizonokenji** [comment]
＞下部は下部でもフッタの少し上に項目付きで設置するのはどうでしょうか。

サンプルまでありがとうございます。イメージしやすいです。
そちらの方が確かに効果的ですね！

＞バナーを作成させていただくことはできませんでしょうか。
そこまでしていただいて、ありがとうございます。
基本デザインは同じもの、なのでおそらく問題ないかと思います！

**Comment by makizonokenji** [comment]
後援の
九州大学大学院芸術工学研究院
九州大学ソーシャルアートラボ
のロゴをいただきました！よろしくお願いします。
九州大学大学院芸術工学研究院のロゴですが、小さい場合はaiデータを送りすね！

![sal](https://cloud.githubusercontent.com/assets/15064449/15660960/fe565cae-271d-11e6-86b8-5b0f30b7f423.png)
![default](https://cloud.githubusercontent.com/assets/15064449/15660961/fe5a043a-271d-11e6-9eb9-4ad327860f78.png)

**Comment by keitakawamoto** [comment]
これまでの開催についてはこのように配置

![image](https://cloud.githubusercontent.com/assets/1661325/15883224/288779d6-2d81-11e6-912d-d4a77557fa3f.png)

急げ！

**Comment by keitakawamoto** [comment]
@makizonokenji 

> 後援の
> 九州大学大学院芸術工学研究院
> 九州大学ソーシャルアートラボ
> のロゴをいただきました！よろしくお願いします。
> 九州大学大学院芸術工学研究院のロゴですが、小さい場合はaiデータを送りすね！

確認しました、ありがとうございます！

**Comment by keitakawamoto** [comment]
支援募金のバナーを作成・設置

![image](https://cloud.githubusercontent.com/assets/1661325/15891345/0f6d3f3e-2daf-11e6-9f14-cb911c9fa170.png)

**Comment by makizonokenji** [comment]
おー！ありがとうございます！！

＞これまでの開催についてはこのように配置

ですが、右の2014の写真が2012の時の写真です。
テーマが「稲荷」でしたので、もし他のものがあれば（鳥居の写真など）
差し替えてもらえると嬉しいです。

他は大丈夫です！ありがとうございます。

**Comment by keitakawamoto** [comment]
@makizonokenji 
なるほど、2012の写真をサイトに使っていたようですね。
ちょうど鳥居の状態があったのでそちらのキャプチャに差し替えました！

![image](https://cloud.githubusercontent.com/assets/1661325/15903712/f6377306-2de8-11e6-8d13-2d088940aa84.png)

**Comment by makizonokenji** [comment]
！
さっそくありがとうございます！

**Comment by keitakawamoto** [comment]
開催概要編集完了。

![image](https://cloud.githubusercontent.com/assets/1661325/15919314/241dfcec-2e4b-11e6-8008-62b8654a8b27.png)

**Comment by keitakawamoto** [comment]
スポンサー関連配置

![image](https://cloud.githubusercontent.com/assets/1661325/15990685/fad347ba-30d5-11e6-91bd-402152549b34.png)

**Comment by makizonokenji** [comment]
連日遅くまでありがとうございます！

①フリーパスチケット制ではなくなりました。プレスリリースには反映していましたが、こちらでの共有ができていませんでした。。よろしくお願いします。

②助成、協賛、後援のロゴはカラーでしょうか？？

**Comment by keitakawamoto** [comment]
@makizonokenji 

フリーパスについてを削除しておきました！
助成、協賛、後援のロゴはもともとメインコンテンツより目立たせないようにモノクロにしていましたが、今のレイアウトでは問題にはならないので、カラーに変更しました！

![image](https://cloud.githubusercontent.com/assets/1661325/16105132/8b381ba2-33c2-11e6-86c8-13b65d4a1734.png)

**Comment by keitakawamoto** [comment]
@makizonokenji 

PCで見た際の全体像、以下のような具合です。
現在スマホで見た時最適化できるよう調整中です。

![screencapture-file-users-keita_kawamoto-itoartsfarm2016-static-index-html-1466063992082](https://cloud.githubusercontent.com/assets/1661325/16109504/27a05f1a-33e4-11e6-83d7-f7864b95c6ec.png)

## メニューについて

幅の問題で、できる限りカテゴリ分けして収納しました。
- 糸島芸農とは？
  - 目的と概要
  - 「発酵する地平」とは
  - プレスリリース
- 開催概要
  - アーティスト
  - イベント / スケジュール
- プロジェクト
- 運営
  - 運営メンバー
  - スタッフブログ / ニュース
  - お問い合わせ
  - これまでの開催
- チケット購入

![image](https://cloud.githubusercontent.com/assets/1661325/16109596/ae24c13e-33e4-11e6-976a-09005d28da2e.png)

![image](https://cloud.githubusercontent.com/assets/1661325/16109597/b40ea934-33e4-11e6-8e03-0459dde81069.png)

![image](https://cloud.githubusercontent.com/assets/1661325/16109619/c036a716-33e4-11e6-9c37-01f832acb7b0.png)

※マウスカーソルを合わせる色が付きます。

![image](https://cloud.githubusercontent.com/assets/1661325/16109642/d6e53540-33e4-11e6-8b03-3761bd11591e.png)

**Comment by makizonokenji** [comment]
みやすく整理までしてくださって、ありがとうございます！
そんな中すみません、、下記２点お願いできないでしょうか？？

【助成、協賛追加】

特別協賛 アサヒビール株式会社
助成 公益財団法人アサヒグループ芸術文化財団

を追加願います。。レイアウトが変わってしまいすみません。。

主催：糸島芸農2016 実行委員会
助成：アサヒ・アート・フェスティバル2016
協賛：Studio Kura
後援：九州大学大学院芸術工学研究院、九州大学ソーシャルアートラボ

↓↓↓↓↓↓↓変更後↓↓↓↓↓↓

主催：糸島芸農2016 実行委員会
助成：アサヒ・アート・フェスティバル2016、
　　   公益財団法人 アサヒグループ芸術文化財団
特別協賛: アサヒビール株式会社
協賛：Studio Kura
後援：九州大学大学院芸術工学研究院、九州大学ソーシャルアートラボ

※ロゴはメールの方にお送りします。

**Comment by keitakawamoto** [comment]
@makizonokenji 

アサヒビールすごい！ 🍺  
- 特別協賛 アサヒビール株式会社
- 助成 公益財団法人アサヒグループ芸術文化財団

追加了解しました。ロゴも確かに受け取りました。
お任せください！ 👍

**Comment by keitakawamoto** [comment]
@makizonokenji 
- 特別協賛 アサヒビール株式会社
- 助成 公益財団法人アサヒグループ芸術文化財団

対応完了しました！

![image](https://cloud.githubusercontent.com/assets/1661325/16899523/45265e1a-4c42-11e6-9ba5-cd2b3f0ea2f0.png)

**Comment by keitakawamoto** [comment]
@makizonokenji 

もろもろの構築が完了しました。お待たせしてしまい、本当に申し訳ありませんでした。
@ecogrammer にWordPressへの実装（http://www.ito-artsfarm.com/ に公開できるように設定）していただけるよう、引き継ぎを行いました。

**Comment by keitakawamoto** [comment]
"レイアウト" に関しては一旦終了ということでこのissueはclose
