### ISSUE TITLE
テーマ実装

### ISSUE THREAD

**Issue by keitakawamoto** [ito-artsfarm/2016website#8]
https://github.com/ito-artsfarm/2016website/issues/6 の実装

**Comment by ecogrammer** [comment]
WordPressのテーマを作る前にstatic（html）でコーディングしたものを作成する。手順としては以下のようなイメージ。
- リポジトリitoartsfarm2016-staticを用意
- コーディングしたものは上記itoartsfarm2016-staticリポジトリにpush
- リポジトリitoartsfarm2016を用意
- WordPressのテーマitoartsfarm2016に実装したものは上記itoartsfarm2016リポジトリにpush
- staging環境で動作検証

**Comment by ecogrammer** [comment]
本番リリース時はざっと以下のような感じ
- http://www.ito-artsfarm.com/ に itoartsfarm2016 テーマインストール
- itoartsfarm2016 テーマ有効化
- Regenerate Thumbnails プラグインで新たしいテーマにあわせたサムネイル画像の再構築
  https://ja.wordpress.org/plugins/regenerate-thumbnails/
- http://www.ito-artsfarm.com/ 公開

**Comment by keitakawamoto** [comment]
ブログについて、混乱しないよう2016タグつけたものだけ表示という制御入れる。
過去サイトについても制御する。
タグを設定した上で、phpで[2016]がついた記事のみ表示という制御をするイメージ。
それをしなければ過去サイトに行った人も年度の違う記事が表示され混乱してしまう。

**Comment by keitakawamoto** [comment]
https://github.com/ito-artsfarm/itoartsfarm2016-static リポジトリ作成done.

**Comment by ecogrammer** [comment]
リポジトリ準備あざす

**Comment by makizonokenji** [comment]
諸々進めてくださってありがとうございます。色々とどたばたしており、遅れててすみません！今日の芸農会議で開催までのスケジュールなどが固まってきましたので、来週中にまとめてリアクションさせてください。よろしくお願いします。

**Comment by keitakawamoto** [comment]
## 

> WordPressのテーマを作る前にstatic（html）でコーディングしたものを作成する。手順としては以下のようなイメージ。
> リポジトリitoartsfarm2016-staticを用意

itoartsfarm2016-staticは以下の3P/Rで完成した。
- https://github.com/ito-artsfarm/itoartsfarm2016-static/pull/1
- https://github.com/ito-artsfarm/itoartsfarm2016-static/pull/2
- https://github.com/ito-artsfarm/itoartsfarm2016-static/pull/3

**Comment by keitakawamoto** [comment]
実装完了
